In [2]:
import numpy as np


In [3]:
from time import process_time

In [4]:
phyton_list=[i for i in range(10000)]
start_time =process_time()
phyton_list=[i+5 for i in phyton_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [5]:
phyton_list=[i for i in range(10000)]
start_time =process_time()
phyton_list=[i+5 for i in phyton_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [6]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape


(4,)

In [10]:
b=np.array([(1,2,3,4,5),(1,4,5,6,7)])
print(b)

[[1 2 3 4 5]
 [1 4 5 6 7]]


In [11]:
b.shape

(2, 5)

In [12]:
c=np.array([(1,2,3,4),(3,4,5,6)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]]


In [13]:
type(c)

numpy.ndarray

In [14]:
x=np.ones([2,4],dtype=int)
print(x)

[[1 1 1 1]
 [1 1 1 1]]


In [15]:
y = np.full((3, 3), 2)
print(y)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [16]:
z=np.full((4,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [17]:
q=np.eye(4)
print(q)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
b=np.random.random((3,4))
print(b)

[[0.11980562 0.71991119 0.08426889 0.28208398]
 [0.40450172 0.08774115 0.27128944 0.29072445]
 [0.94795841 0.45445547 0.7918512  0.06067396]]


In [19]:
c=np.random.randint(10,100,(3,4))
print(c)

[[26 66 51 84]
 [92 23 59 29]
 [77 89 38 12]]


In [20]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [21]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
list2=[1,2,3,4,5]
np_array=np.asarray(list2)
print(np_array)

[1 2 3 4 5]


In [23]:
c=np.random.randint(10,40,(5,5))
print(c)

[[19 18 17 26 33]
 [33 31 11 21 20]
 [14 16 18 27 34]
 [29 38 20 38 10]
 [26 27 24 12 16]]


In [24]:
print(c.shape)

(5, 5)


In [25]:
print(c.ndim)

2


In [26]:
print(c.size)

25


In [27]:
print(c.dtype)

int32


In [28]:
# mathematical operations performed on NP array
list1=[1,2,3,4]
list2=[2,3,4,5]
print(list1+list2)

[1, 2, 3, 4, 2, 3, 4, 5]


In [29]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)

[[9 2 9]
 [3 5 0]
 [6 5 6]]
[[19 12 16]
 [14 17 13]
 [17 12 15]]
[[28 14 25]
 [17 22 13]
 [23 17 21]]


In [30]:
print(a/b)

[[0.47368421 0.16666667 0.5625    ]
 [0.21428571 0.29411765 0.        ]
 [0.35294118 0.41666667 0.4       ]]


In [31]:
print(np.add(a,b))

[[28 14 25]
 [17 22 13]
 [23 17 21]]


In [32]:
print(np.subtract(a,b))

[[-10 -10  -7]
 [-11 -12 -13]
 [-11  -7  -9]]


In [33]:
 array=np.random.randint(0,10,(2,3))
 print(array)

[[8 8 6]
 [0 0 0]]


In [34]:
trans=np.transpose(array)
print(trans)

[[8 0]
 [8 0]
 [6 0]]
